hugoblox:
  schema: "2.0"
  identity:
    name: Rachel Coxhead
    type: person
    tagline: Software Developer
    description: I am a junior developer curious about and driven to make user-centred digital experiences. My work focuses on web and mobile solutions in an Agile environment.
  theme:
    mode: light
    pack: default
    colors:
      primary: cyan
      secondary: "cyan"
      neutral: ""
    colors_light:
      primary: violet
      secondary: violet
      neutral: ""
    colors_dark:
      primary: ""
      secondary: ""
      neutral: ""
    surfaces: {}
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: false
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: Â© {2026} {Rachel Coxhead}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
